/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 */
import com.bmuschko.gradle.docker.tasks.image.Dockerfile
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    signing
    alias(libs.plugins.graalvm)
    alias(libs.plugins.cyclonedx)
    alias(libs.plugins.jreleaser)
    alias(libs.plugins.shadow)
    alias(libs.plugins.docker.java)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    // This dependency is used by the application.
    implementation(libs.picocli.shell)
    implementation(libs.picocli.codegen)
    annotationProcessor(libs.picocli.codegen)
    implementation(libs.jansi)
    implementation(libs.dagger)
    annotationProcessor(libs.dagger.compiler)
}

application {
    mainClass.set("de.codepitbull.cli.Cli")
}
tasks.named<ShadowJar>("shadowJar") {
    archiveClassifier.set("") // Ensures the shadow JAR is the main artifact
}

signing {
    useGpgCmd()
    sign(tasks.named<ShadowJar>("shadowJar").get())
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

graalvmNative {
    toolchainDetection.set(true)
    binaries {
        named("main") {
            javaLauncher.set(javaToolchains.launcherFor {
                languageVersion.set(JavaLanguageVersion.of(22))
                vendor.set(JvmVendorSpec.matching("Oracle Corporation"))
            })
        }
    }
}

tasks.register<Dockerfile>("createDockerfile") {
    from("eclipse-temurin:21-jre")
    copyFile("build/libs/cli.jar", "/cli/cli.jar")
    entryPoint("java")
    defaultCommand("-cp", "/cli/cli.jar", "de.codepitbull.cli.Server")
    exposePort(8080)
}

docker {
    javaApplication {
        baseImage.set("eclipse-temurin:21-jre")
        maintainer.set("Jochen Mader")
        ports.set(listOf(8080))
        images.set(setOf("hello:latest"))
        jvmArgs.set(listOf("-Xms256m", "-Xmx2048m"))
        args.set(listOf("server"))
    }
}

tasks.cyclonedxBom {
    setIncludeConfigs(listOf("runtimeClasspath"))
    setSkipConfigs(listOf("compileClasspath", "testCompileClasspath"))
    setProjectType("application")
}


//Reproducible builds
tasks.withType<AbstractArchiveTask>().configureEach {
    isPreserveFileTimestamps = false
    isReproducibleFileOrder = true
}

tasks.named("distZip") {
    dependsOn(tasks.named("shadowJar"))
}

tasks.named("distTar") {
    dependsOn(tasks.named("shadowJar"))
}

tasks.named("startScripts") {
    dependsOn(tasks.named("shadowJar"))
}

tasks.named("startShadowScripts") {
    dependsOn(tasks.named("jar"))
}

tasks.named("signShadowJar") {
    dependsOn(tasks.named("jar"))
}

jreleaser {
    // Configure JReleaser to use the external YAML file
    configFile.set(file("jreleaser.yml"))
}
